// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebLibrary.DAL;

#nullable disable

namespace WebLibrary.DAL.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231214101210_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Main")
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BooksId")
                        .HasColumnType("uuid");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook", "Main");
                });

            modelBuilder.Entity("WebLibrary.DAL.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .HasMaxLength(560)
                        .HasColumnType("character varying(560)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Authors", "Main");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4808d76e-e4af-4985-8056-cb214a9977bf"),
                            Description = "Dame Agatha Mary Clarissa Christie, was an English writer known for her 66 detective novels and 14 short story collections, particularly those revolving around fictional detectives Hercule Poirot and Miss Marple.",
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = new Guid("497da1e8-04e0-4571-a404-d1983c132535"),
                            Description = "William Shakespeare was an English playwright, poet and actor.",
                            Name = "William Shakespeare"
                        },
                        new
                        {
                            Id = new Guid("0e2786ff-fd34-4551-a4ca-27820cbd0420"),
                            Name = "Barbara Cartland"
                        },
                        new
                        {
                            Id = new Guid("2616bc1b-75ee-414e-a9ee-b132526a57f6"),
                            Name = "Danielle Steel"
                        });
                });

            modelBuilder.Entity("WebLibrary.DAL.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<byte[]>("Cover")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Books", "Main");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("WebLibrary.DAL.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebLibrary.DAL.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
